FROM tensorflow/tensorflow:1.13.1-gpu-py3

RUN apt-get update \
	&& apt-get install -y curl zip unzip python3 python3-dev python3-pip python3-tk protobuf-compiler python3-lxml libglib2.0-0 git\
    && pip3 install Cython
# COPY ./tensorflow ./tensorflow
RUN git clone https://github.com/tensorflow/models.git ./tensorflow/models

WORKDIR /app
COPY ./app /app/

RUN chmod 777 /app/latest_protobuf.sh
RUN /app/latest_protobuf.sh

RUN cd /tensorflow/models/research \
    && protoc object_detection/protos/*.proto --python_out=. \
    && python3 setup.py sdist \
    && (cd slim && python3 setup.py sdist)

RUN pip3 install -r /app/requirements-gpu.txt
ENV PYTHONPATH=$PYTHONPATH:/tensorflow/models:/tensorflow/models/slim
ENV ENVIRONMENT production
ENV PYTHONPATH /tensorflow/models/research:/tensorflow/models/research/slim
DB_NAME=uo-vision-1
DB_USER=uo
DB_PASS=vision
DB_DOM AIN=database.urbanobservatory.ac.uk
DB_PORT=5234
ENVIRONMENT='production'
MODEL='/ntk38/scripts/uo-object_counting/app/fig_frcnn_rebuscov-3.pb'
LABELS ='/ntk38/scripts/uo-object_counting/app/rebuscov-classes-3.pbtxt'
GPU_MEMORY=0.25
MIN_CONF=0.25
W=640
H=480
CUDA_VISIBLE_DEVICES=1
IP=0
PYTHONPATH=/models/research:/models/research/slim


RUN apt-get update \
    && apt-get install -y supervisor # Installing supervisord
ADD supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# ENTRYPOINT ["/usr/bin/supervisord"]

ENTRYPOINT python3 ./allinone.py
